### PR TITLE
Added ram check

### PR DESCRIPTION
**Pull request by Max-109**
I noticed that tab unloader works always and the only thing which stops it - time. i thought ram check would make it better, because i think there is no point of unloading tabs if we have plenty of ram capacity left.

### CODE REVIEW

**Review by rakzoser — COMMENTED** [review]
these files were added by mistake, the only change is in 'ZenTabUnloader.mjs'

**Comment by mauro-balades** [comment]
Could you please delete them?

**Comment by Max-109** [comment]
> Could you please delete them?

Sure, I did that. The only thing left to add this feature is to include it in the browser menu itself. However, since it's in another repository, I can't do that (it's just one line)

**Comment by mauro-balades** [comment]
Thanks a lot!

**Comment by mauro-balades** [comment]
Wait, have you tested this? The function doesnt exist and there are syntax errors...

**Pull request merged**
